### ISSUE TITLE
"cannot load such file -- sinatra/base" on Heroku

### ISSUE THREAD

**Issue by edvakf** [idobata/idobata-hooks#36]
The logs say;

```
2015-02-19T19:02:56.773175+00:00 heroku[web.1]: Starting process with command `bundle exec rackup -p 38146`
2015-02-19T19:02:58.906988+00:00 app[web.1]: fatal: Not a git repository (or any of the parent directories): .git
2015-02-19T19:02:59.195232+00:00 app[web.1]: fatal: Not a git repository (or any of the parent directories): .git
2015-02-19T19:03:00.212688+00:00 app[web.1]: /app/app.rb:6:in `require': cannot load such file -- sinatra/base (LoadError)
2015-02-19T19:03:00.212714+00:00 app[web.1]: 	from /app/app.rb:6:in `<top (required)>'
2015-02-19T19:03:00.212733+00:00 app[web.1]: 	from /app/config.ru:3:in `require_relative'
2015-02-19T19:03:00.212751+00:00 app[web.1]: 	from /app/config.ru:3:in `block in <main>'
2015-02-19T19:03:00.212770+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/builder.rb:55:in `instance_eval'
2015-02-19T19:03:00.212788+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/builder.rb:55:in `initialize'
2015-02-19T19:03:00.212807+00:00 app[web.1]: 	from /app/config.ru:in `new'
2015-02-19T19:03:00.212825+00:00 app[web.1]: 	from /app/config.ru:in `<main>'
2015-02-19T19:03:00.212844+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/builder.rb:49:in `eval'
2015-02-19T19:03:00.212862+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/builder.rb:49:in `new_from_string'
2015-02-19T19:03:00.212880+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/builder.rb:40:in `parse_file'
2015-02-19T19:03:00.212900+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/server.rb:277:in `build_app_and_options_from_config'
2015-02-19T19:03:00.212919+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/server.rb:199:in `app'
2015-02-19T19:03:00.212937+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/server.rb:314:in `wrapped_app'
2015-02-19T19:03:00.212955+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/server.rb:250:in `start'
2015-02-19T19:03:00.212994+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/server.rb:141:in `start'
2015-02-19T19:03:00.213015+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/bin/rackup:4:in `<top (required)>'
2015-02-19T19:03:00.213035+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/bin/rackup:23:in `load'
2015-02-19T19:03:00.213054+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/bin/rackup:23:in `<main>'
2015-02-19T19:03:01.016363+00:00 heroku[web.1]: Process exited with status 1
2015-02-19T19:03:01.027770+00:00 heroku[web.1]: State changed from starting to crashed
```

My config vars are;

```
BUNDLE_WITHOUT : test
GIT_DISCOVERY_ACROSS_FILESYSTEM : true
IDOBATA_HOOK_HOST : (my app's host)
IDOBATA_HOOK_URL : https://idobata.io/hook/generic/xxxxxxxxxx
LANG : en_US.UTF-8
RACK_ENV : production
```

**Comment by edvakf** [comment]
Note: `bundle install --path vendor/bundle` succeeds in `heroku run bash`

**Comment by tricknotes** [comment]
> Gems in the groups development and test were not installed.

Hmm, this is strange.
We expect `development` group is installed on Heroku.

Now I create a new Heroku environment and it works as we expected.
I want to know the difference of these config probably related with bundler.

Could you provide the result of `heroku run bundle config`?

The following is mine:
```
Running `bundle config` attached to terminal... up, run.1378
Settings are listed in order of priority. The top value will be used.
frozen
Set for your local app (/app/.bundle/config): "1"
Set for the current user (/app/.bundle/config): "1"

path
Set for your local app (/app/.bundle/config): "vendor/bundle"
Set for the current user (/app/.bundle/config): "vendor/bundle"

bin
Set for your local app (/app/.bundle/config): "vendor/bundle/bin"
Set for the current user (/app/.bundle/config): "vendor/bundle/bin"

jobs
Set for your local app (/app/.bundle/config): "4"
Set for the current user (/app/.bundle/config): "4"

without
Set for your local app (/app/.bundle/config): "test"
Set via BUNDLE_WITHOUT: "test"
Set for the current user (/app/.bundle/config): "test"

disable_shared_gems
Set for your local app (/app/.bundle/config): "1"
Set for the current user (/app/.bundle/config): "1"
```

**Comment by edvakf** [comment]
here it is.

```
Running `bundle config` attached to terminal... up, run.6867
Settings are listed in order of priority. The top value will be used.
frozen
Set for your local app (/app/.bundle/config): "1"
Set for the current user (/app/.bundle/config): "1"

path
Set for your local app (/app/.bundle/config): "vendor/bundle"
Set for the current user (/app/.bundle/config): "vendor/bundle"

bin
Set for your local app (/app/.bundle/config): "vendor/bundle/bin"
Set for the current user (/app/.bundle/config): "vendor/bundle/bin"

jobs
Set for your local app (/app/.bundle/config): "4"
Set for the current user (/app/.bundle/config): "4"

without
Set for your local app (/app/.bundle/config): "development:test"
Set via BUNDLE_WITHOUT: "test"
Set for the current user (/app/.bundle/config): "development:test"

disable_shared_gems
Set for your local app (/app/.bundle/config): "1"
Set for the current user (/app/.bundle/config): "1"
```

**Comment by tricknotes** [comment]
Thanks. I know what was happening.

Heroku requires a new deploy to update `bundle config` after `BUNDLE_WITHOUT` modified.

### NG

```
$ git push heroku master
$ heroku config:set BUNDLE_WITHOUT=test
```

### OK

```
$ heroku config:set BUNDLE_WITHOUT=test
$ git push heroku master
```

or 

```
$ git push heroku master
$ heroku config:set BUNDLE_WITHOUT=test
$ git push heroku master
```

Could you try deploy once more?
If you have no changes, you can force push with previous revision. (this is a bit tricky)

```
$ git push heroku HEAD~1:master
$ git push heroku master
```

**Comment by edvakf** [comment]
It worked! Thank you very much for your help.
